import { ObjectId } from "mongodb";

export type Product = {
    _id?: ObjectId; // Optional, will be generated by MongoDB
    name: string;
    description: string;
    price: number;
    category: string; // Example categories: "Fitness Gear", "Supplements", "Nutrition"
    imageURL: string; // URL of the product image
    availability: boolean; // true if in stock, false if out of stock
};
